version : "3.9"
services:
  mongo-svc:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
  auth-svc:
    build: .
    container_name: auth-svc-container
    ports:
      - "9090:9090"