name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build - Maven clean install
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt-hotspot'
        java-version: '11'
    - name: Maven - Build
      run: mvn clean install
    - name: Docker - Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
    - name: Docker - Build image
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} build
    - name: Docker - Push image
      run: docker push $REPO
